name: 'Upload a Release Asset'
description: 'Upload a release asset to an existing release in your repository'
author: 'GitHub'
inputs:
  token:
    description: 'Token used for access, defaults github.token'
    required: false
    default: ${{ github.token }}
  release_id:
    description: 'Id of the release you want the asset attached to'
    required: true
  asset_path:
    description: 'The path to the asset you want to upload'
    required: true
  asset_name:
    description: 'The name you want the asset to have'
    required: true
  asset_content_type:
    description: 'The content-type of the asset you want to upload. See the supported Media Types here: https://www.iana.org/assignments/media-types/media-types.xhtml for more information'
    required: true
outputs:
  browser_download_url:
    description: 'The URL users can navigate to in order to download the uploaded asset'
branding:
  icon: 'package'
  color: 'gray-dark'
runs:
  using: 'node16'
  main: 'dist/index.js'
