name: "units-test"
on:
  pull_request:
    paths-ignore:
      - '**.md'
  push:
    branches:
      - main
    paths-ignore:
      - '**.md'

jobs:
  # unit tests
  units:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - run: npm ci
    - run: npm test

  live:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: npetzall/auto-version-action@main
        id: auto-version
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
      - name: Package upload-release-asset dist
        run: zip upload-release-asset-${{ steps.auto-version.outputs.auto-version }}.zip -r dist action.yml
      - uses: npetzall/auto-release-action@main
        id: auto-release
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
      - uses: ./
        with:
          release_id: ${{ steps.auto-release.outputs.release-id }}
          asset_path: ./upload-release-asset-${{ steps.auto-version.outputs.auto-version }}.zip
          asset_name: upload-release-asset-${{ steps.auto-version.outputs.auto-version }}.zip
          asset_content_type: application/zip
